download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", "hid.csv", method="curl")
hid = read.csv("hid.csv")
mdlr = subset(hid, hid$VAL == 24)
print(nrow(mdlr))

library(xlsx)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx", "ngap.xlsx", method="curl")
dat <- read.xlsx("ngap.xlsx", 1, colIndex=c(7:15), rowIndex=c(18:23))
val <- sum(dat$Zip * dat$Ext, na.rm = TRUE)
print(val)

library(XML)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml", "restaurants.xml", method="curl")
d = xmlParse("restaurants.xml", useInternal=TRUE)
r = xmlRoot(d)
zip = xpathSApply(r, '//zipcode', xmlValue)
print(length(zip[zip == "21231"]))

library(data.table)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv", "pid.csv", method = "curl")
DT <- data.table(fread("pid.csv"))
tables()
print(system.time(DT[,mean(pwgtp15),by=SEX]))
print(system.time(sapply(split(DT$pwgtp15,DT$SEX),mean)))
print(system.time(mean(DT[DT$SEX==1,]$pwgtp15))); print(system.time(mean(DT[DT$SEX==2,]$pwgtp15)))
print(system.time(rowMeans(DT)[DT$SEX==1])); print(system.time(rowMeans(DT)[DT$SEX==2]))
print(system.time(tapply(DT$pwgtp15,DT$SEX,mean)))
print(system.time(mean(DT$pwgtp15,by=DT$SEX)))
